[package]
name = "pipe-cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "^0.35.2", features = ["raw-window-handle"] }
wgpu = "^0.14.0"
pollster = "^0.2.5"
raw-window-handle = "0.5.0"
raw-window-handle_0_4_2 = { package = "raw-window-handle", version = "0.4.2" }
